### ISSUE TITLE
[question] Does this lib support subscription?

### ISSUE THREAD

**Issue by onichandame** [graphql-community/koa-graphql#140]
I cannot find any example of using this lib to handle subscriptions. Is it even supported? If so, please point me to an example. Thanks

**Comment by jgcmarins** [comment]
check [graphql-helix](https://github.com/contrawork/graphql-helix) for a better subscription implementation

**Comment by onichandame** [comment]
> check [graphql-helix](https://github.com/contrawork/graphql-helix) for a better subscription implementation

Thanks, will take a look. I now use Nest.js instead so this issue is irrelevant for now.

**Comment by wrongbyte** [comment]
I know this issue is marked as closed, but for those looking for it: probably not, at least if you want to use `graphql-ws`. I'm getting `Connection Closed: 4406 Subprotocol not acceptable` when trying to implement a subscription endpoint. 
There's a similar problem around Apollo (https://github.com/enisdenjo/graphql-ws/discussions/237) where the reason is that `graphql-ws` is not supported - which I believe is the same problem here.
